apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configmonitors.serviceconfig.metalk8s.scality.com
spec:
  scope: Namespaced
  group: serviceconfig.metalk8s.scality.com
  names:
    kind: ConfigMonitor
    singular: configmonitor
    plural: configmonitors
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            configMap:
              type: string
              description: "Name of the ConfigMap to watch for changes"
            podSelector:
              type: object
              description: "Label selector used for selecting Pods"
              additionalProperties:
                type: string
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true