apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ solution }}-operator-config
  namespace: {{ namespace }}
data:
  operator.yaml: |
    apiVersion: solutions.metalk8s.scality.com/v1alpha1
    kind: OperatorConfig
    repositories:
{%- for version_info in pillar.metalk8s.solutions.available.get(solution, []) %}
      - version: {{ version_info.version }}
        repository: {{ registry }}/{{ version_info.id }}
{%- endfor %}
