apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ solution }}-operator-config
  namespace: {{ namespace }}
data:
  operator.yaml: |
    apiVersion: solutions.metalk8s.scality.com/v1alpha1
    kind: OperatorConfig
    repositories:
{%- for version_info in pillar.metalk8s.solutions.available.get(solution, []) %}
      {{ version_info.version }}:
        - endpoint: {{ registry }}/{{ version_info.id }}
          images:
            {{ version_info.config.images | yaml(False) | indent(12) }}
{%- endfor %}
