{%- set role_binding_name = "{}-operator-{}-{}".format(
  solution, role_kind | lower, role_name
) %}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ role_binding_name[:63] }}
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-operator
    app.kubernetes.io/name: {{ solution }}-operator
    app.kubernetes.io/instance: {{ solution }}-operator
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: {{ solution }}
subjects:
- kind: ServiceAccount
  name: {{ solution }}-operator
roleRef:
  kind: {{ role_kind }}
  name: {{ role_name }}
  apiGroup: rbac.authorization.k8s.io
