apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ solution }}-operator
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-operator
    app.kubernetes.io/name: {{ solution }}-operator
    app.kubernetes.io/instance: {{ solution }}-operator
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: {{ solution }}
rules:
{# TODO: make those configurable #}
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - {{ solution }}-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
{%- if custom_api_groups %}
- apiGroups: {{ custom_api_groups | tojson }}
  resources:
  - '*'
  verbs:
  - '*'
{%- endif %}
