kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ solution }}-operator
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-operator
    app.kubernetes.io/name: {{ solution }}-operator
    app.kubernetes.io/instance: {{ solution }}-operator
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: {{ solution }}
subjects:
- kind: ServiceAccount
  name: {{ solution }}-operator
roleRef:
  kind: Role
  name: {{ solution }}-operator
  apiGroup: rbac.authorization.k8s.io
