default_language_version:
  python: python3.6

repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Formatting Python

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        name: Lint Python (non-salt)
        # Linting for non-salt files (buildchain and python not executed
        # by salt directly)
        additional_dependencies:
          - 'pyenchant~=2.0'
          - 'doit~=0.32.0'
          - 'docker~=4.1.0'
          - 'PyYAML~=5.3.1'
        files: >
          (?x)^(
              buildchain/dodo.py|
              buildchain/buildchain|
              packages/debian/common/download_packages.py|
              salt/metalk8s/volumes/files/sparse_volume_cleanup.py
          )$
      - id: pylint
        name: Lint Salt
        # Linting for salt files only in directory "salt/_<module>/<module_name>.py"
        files: salt/_.*/.*\.py
        additional_dependencies: ['saltpylint==2020.9.28']
        args:
          - --rcfile=salt/.pylintrc
          - --ignore=metalk8s_package_manager_apt.py

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        # We want this hook to be part of "pylint" so that if we run
        # `pre-commit run pylint` we include this hook
        alias: pylint
        name: Python typing
        # Only check typing for typed files
        files: >
          (?x)^(
              buildchain/dodo.py|
              buildchain/buildchain/.*|
              packages/debian/common/download_packages.py
          )$
        args:
          - --strict

  - repo: https://github.com/warpnet/salt-lint
    rev: v0.5.1
    hooks:
      - id: salt-lint
