apiVersion: v1
kind: Pod
metadata:
  name: demo-eve-hanger
spec:
  containers:
  - name: worker
    image: {{ images['demo-eve-hanger'] }}
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
    volumeMounts:
      - name: worker-workspace
        mountPath: /home/eve/workspace
  volumes:
    - name: worker-workspace
      emptyDir: {}
