- name: 'Copy Calico monitoring deployment files'
  copy:
    src: '{{ item.file }}'
    dest: '{{ calico_monitoring_addon_dir }}/'
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755
  with_items: '{{ calico_monitoring_manifests }}'
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

#- name: 'Deploy Calico monitoring'
#  kube:
#    kubectl: '{{ bin_dir }}/kubectl'
#    filename: '{{ calico_monitoring_addon_dir }}/{{ item.file | basename }}'
#    namespace: '{{ item.namespace }}'
#    state: 'latest'
#  with_items: '{{ calico_monitoring_manifests }}'
#  run_once: true
#  delegate_to: "{{ groups['kube-master'][0] }}"
