apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmonitor-operator
  namespace: kube-system
  labels:
    app: configmonitor-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmonitor-operator
  template:
    metadata:
      labels:
        app: configmonitor-operator
    spec:
      serviceAccountName: configmonitor-operator
      tolerations:
      - key: "node-role.kubernetes.io/bootstrap"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/infra"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: configmonitor-operator
        image: {{ build_image_name('configmonitor-operator') }}
        imagePullPolicy: Always
        env:
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace