apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: config-monitor-crd
rules:
- apiGroups:
  - ""
  resources:
  - configmonitor
  - configmonitor/finalizers
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - watch
