annotations:
  artifacthub.io/changes: |
    - Added support for priority class name
  artifacthub.io/images: |
    - name: dex
      image: ghcr.io/dexidp/dex:v2.28.1
apiVersion: v2
appVersion: 2.28.1
description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable
  connectors.
home: https://dexidp.io/
icon: https://dexidp.io/favicon.png
keywords:
- oidc
- oauth
- identity-provider
- saml
kubeVersion: '>=1.14.0-0'
maintainers:
- email: mark.sagikazar@gmail.com
  name: sagikazarmark
  url: https://sagikazarmark.hu
name: dex
sources:
- https://github.com/dexidp/dex
- https://github.com/dexidp/helm-charts/tree/master/charts/dex
type: application
version: 0.4.0
