image: '__image__(dex)'

nodeSelector:
  node-role.kubernetes.io/infra: ''

tolerations:
  - key: "node-role.kubernetes.io/bootstrap"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"

replicas: '__var__(dex.spec.deployment.replicas)'

# grpc support
grpc: false

# https termination by dex itself
https: true

service:
  clusterIP: '__var__(salt.metalk8s_network.get_oidc_service_ip())'

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx-control-plane"
  path: /oidc
  hosts:
    - null

extraVolumes:
  - name: dex-login
    configMap:
      name: dex-login

extraVolumeMounts:
  - name: dex-login
    mountPath: /web/themes/scality

podAnnotations:
  # Override default checksum as we want to manage it with salt
  checksum/config: '__slot__:salt:metalk8s_kubernetes.get_object_digest(kind="Secret", apiVersion="v1", namespace="metalk8s-auth", name="dex", path="data:config.yaml")'

certs:
  web:
    create: false
  grpc:
    create: false

# NOTE: Ignore these values, the configuration is computed from
#       - salt/metalk8s/addons/dex/config/dex.yaml
#       - salt/metalk8s/addons/dex/deployed/service-configuration.sls
config:
  issuer: 'dex.scality.com'
  web:
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  frontend:
    theme: "scality"
    issuer: "MetalK8s"

  oauth2:
    alwaysShowLoginScreen: true
    skipApprovalScreen: true
    responseTypes: ["code", "token", "id_token"]

  expiry:
    signingKeys: "6h"
    idTokens: "24h"

  staticClients: []

  enablePasswordDB: true
  staticPasswords: []
