image: '__image__(dex)'

nodeSelector:
  node-role.kubernetes.io/infra: ''

tolerations:
  - key: "node-role.kubernetes.io/bootstrap"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"

replicas: '__var__(dex.spec.deployment.replicas)'

# grpc support
grpc: false

# https termination by dex itself
https: true

service:
  clusterIP: '__var__(salt.metalk8s_network.get_oidc_service_ip())'

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx-control-plane"
  path: /oidc
  hosts:
    - null

extraVolumes:
  - name: dex-login
    configMap:
      name: dex-login

extraVolumeMounts:
  - name: dex-login
    mountPath: /web/themes/scality

certs:
  web:
    create: false
  grpc:
    create: false

config:
  issuer: '__url__(https://{{ grains.metalk8s.control_plane_ip }}:8443/oidc)'
  web:
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  frontend:
    theme: "scality"
    issuer: "MetalK8s"

  connectors: '__var_tojson__(dex.spec.connectors)'

  oauth2:
    alwaysShowLoginScreen: true
    skipApprovalScreen: true
    responseTypes: ["code", "token", "id_token"]

  expiry:
    signingKeys: "6h"
    idTokens: "24h"

  staticClients:
  - id: oidc-auth-client
    redirectURIs:
    - 'urn:ietf:wg:oauth:2.0:oob'
    name: 'oidc-auth-client'
    secret: "lkfa9jaf3kfakqyeoikfjakf93k2l"
    trustedPeers:
    - metalk8s-ui
    - grafana-ui
  - id: metalk8s-ui
    redirectURIs:
    - '__url__(https://{{ grains.metalk8s.control_plane_ip }}:8443/oauth2/callback)'
    name: 'MetalK8s UI'
    secret: "ybrMJpVMQxsiZw26MhJzCjA2ut"
  - id: grafana-ui
    name: 'Grafana UI'
    redirectURIs:
    - '__url__(https://{{ grains.metalk8s.control_plane_ip }}:8443/grafana/login/generic_oauth)'
    secret: "4lqK98NcsWG5qBRHJUqYM1"

  enablePasswordDB: '__var__(dex.spec.localuserstore.enabled)'

  staticPasswords: '__var_tojson__(dex.spec.localuserstore.userlist)'
