existingConfigMap: metallb-config

controller:
  image:
    registry: null
    repository: '__image__(metallb-controller)'

  nodeSelector:
    node-role.kubernetes.io/master: ''

  tolerations:
    - key: "node-role.kubernetes.io/bootstrap"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/infra"
      operator: "Exists"
      effect: "NoSchedule"

  podAnnotations:
    checksum/config: '__slot__:salt:metalk8s_kubernetes.get_object_digest(kind="ConfigMap", apiVersion="v1", namespace="metalk8s-loadbalancing", name="metallb-config", path="data:config")'

speaker:
  image:
    registry: null
    repository: '__image__(metallb-speaker)'

  nodeSelector:
    node-role.kubernetes.io/master: ''

  tolerations:
    - key: "node-role.kubernetes.io/bootstrap"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/infra"
      operator: "Exists"
      effect: "NoSchedule"
