---

- name: 'install Elasticsearch ServiceMonitor'
  vars:
    values_file: '{{ role_path }}/files/elasticsearch-exporter/values.yml'
  helm_cli:
    release: '{{ elasticsearch_exporter_release_name }}'
    chart:
      name: '{{ elasticsearch_exporter_chart }}'
      version: '{{ elasticsearch_exporter_version }}'
      repo: '{{ elasticsearch_exporter_repo }}'
    namespace: '{{ elasticsearch_exporter_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: >-
      {{ [
        lookup('file', values_file) | from_yaml
      ] + elasticsearch_exporter_external_values }}
    wait: '{{ helm_wait | bool }}'
    state: '{{ helm_state }}'
  register: elasticsearch_exporter_helm_install
  run_once: true

- debug:
    var: elasticsearch_exporter_helm_install
  run_once: true
  when: debug | bool

- name: 'copy ElasticSearch Exporter ServiceMonitor file'
  copy:
    src: 'elasticsearch-exporter/servicemonitor.yml'
    dest: '{{ es_addon_dir }}/'
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

#- name: 'deploy ElasticSearch Exporter ServiceMonitor'
#  kube:
#    kubectl: '{{ bin_dir }}/kubectl'
#    filename: '{{ es_addon_dir }}/servicemonitor.yml'
#    namespace: '{{ elasticsearch_exporter_namespace }}'
#    state: 'latest'
#  run_once: true
#  delegate_to: "{{ groups['kube-master'][0] }}"
