apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ solution }}-ui
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-ui
    app.kubernetes.io/name: {{ solution }}-ui
    app.kubernetes.io/instance: {{ solution }}-ui
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: {{ solution }}
data:
  config.json: |
    {"url": "/api/kubernetes"}
  theme.json: |
    {"brand": {"primary": "#403e40", "secondary": "#e99121"}}
