apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ solution }}-ui
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-ui
    heritage: {{ solution }}
    app.kubernetes.io/name: {{ solution }}-ui
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: {{ solution }}
    # UIs are deployed and managed by Salt, provided with MetalK8s
    app.kubernetes.io/managed-by: salt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ solution }}-ui
  template:
    metadata:
      labels:
        app: {{ solution }}-ui
        heritage: {{ solution }}
        app.kubernetes.io/name: {{ solution }}-ui
        app.kubernetes.io/instance: {{ solution }}-ui
        app.kubernetes.io/version: {{ version }}
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: {{ solution }}
        # UIs are deployed and managed by Salt, provided with MetalK8s
        app.kubernetes.io/managed-by: salt
    spec:
      tolerations:
      # UIs are deployed on "infra" Nodes, so we need these tolerations
      - key: "node-role.kubernetes.io/bootstrap"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/infra"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      containers:
        - name: {{ solution }}-ui
          image: "{{ repository }}/{{ image_name }}:{{ image_tag }}"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          volumeMounts:
          - name: ui-config
            mountPath: /etc/{{ solution }}/ui
            readOnly: true
      volumes:
        - name: ui-config
          configMap:
            name: {{ solution }}-ui
