apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ solution }}-ui
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/managed-by: salt
    app.kubernetes.io/name: {{ solution }}-ui
    app.kubernetes.io/part-of: {{ solution }}
    heritage: {{ solution }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-control-plane"
spec:
  rules:
  - http:
      paths:
      - path: /env/{{ environment }}/{{ solution }}(/|$)(.*)
          backend:
            serviceName: {{ solution }}-ui
            servicePort: 80
