apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ solution }}-ui
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-ui
    app.kubernetes.io/name: {{ solution }}-ui
    app.kubernetes.io/instance: {{ solution }}-ui
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: {{ solution }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-control-plane"
spec:
  rules:
  - http:
      paths:
      - path: /env/{{ environment }}/{{ solution }}(/|$)(.*)
        backend:
          serviceName: {{ solution }}-ui
          servicePort: 80
