kind: Service
apiVersion: v1
metadata:
  name: {{ solution }}-ui
  namespace: {{ namespace }}
  labels:
    app: {{ solution }}-ui
    heritage: {{ solution }}
    app.kubernetes.io/name: {{ solution }}-ui
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: {{ solution }}
    app.kubernetes.io/managed-by: salt
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ solution }}-ui
  type: NodePort
