---
version: "0.2"

branches:
  "*":
    stage: demo-hang

stages:
  demo-hang:
    worker:
      type: kube_pod
      path: eve/workers/demo-eve-hang/pod.yaml
      images:
        demo-eve-hanger: eve/workers/demo-eve-hang
    steps:
      - ShellCommand:
          name: Demonstrate Eve hanging
          command: |
            # Background process
            sleep 3600 &
            BG_PID=$!
            # Foreground process
            echo "Doing some tests"
            sleep 2
            echo "Tests done!"
            # Clean up
            kill -9 $BG_PID
            echo "All cleaned up!"
