version: '0.2'

branches:
  default:
    stage: pre-merge

stages:

  pre-merge:
    worker:
      type: local
    steps:
      - TriggerStages:
          name: Trigger build and lint stages simultaneously
          stage_names:
            - build
            - lint

  build:
    worker:
      type: kube_pod
      path: eve/workers/pod-builder/pod.yaml
      images:
          docker-builder: eve/workers/pod-builder
    steps:
    - ShellCommand:
        name: Wait for Docker daemon to be ready
        command: |
          bash -c '
          for i in {1..10}
          do
            docker --version &> /dev/null && exit
            sleep 2
          done
          echo "Could not reach Docker daemon from buildbot worker" >&2
          exit 1'
        haltOnFailure: true
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        method: clobber
        retryFetch: true
        haltOnFailure: true
    - ShellCommand:
        name: build everything
        command: make
    - ShellCommand:
        name: Put the iso file in a separate folder
        command: mkdir iso && cp _build/metalk8s.iso _build/SHA256SUM iso
    - Upload:
        name: upload artifacts
        source: iso/
        urls:
          - "*.iso"
          - "SHA256SUM"

  lint:
    worker:
      type: kube_pod
      path: eve/workers/pod-linter/pod.yaml
      images:
        docker-linter: eve/workers/pod-linter
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: Run all linting targets
        command: make lint
        flunkOnFailure: false
        haltOnFailure: false
