version: '0.2'
branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*, dependabot/*, documentation/*, release/*:
    stage: pre-merge
stages:
  pre-merge:
    worker:
      type: local
    steps:
    - ShellCommand:
        name: Set build status to 'FAILED'
        command: mkdir -p build_status && echo -n 'FAILED' > build_status/.final_status
        haltOnFailure: true
        hideStepIf: true
    - Git:
        name: Git pull
        repourl: '%(prop:git_reference)s'
        method: clobber
        retryFetch: true
        haltOnFailure: true
        hideStepIf: true
    - ShellCommand:
        name: Read last build artifacts URL
        command: bash eve/scripts/read-last-build-status.sh
        env:
          ARTIFACTS_NAME: '%(prop:artifacts_name)s'
    - SetPropertyFromCommand:
        name: (prop) Last build artifacts URL
        property: last_artifacts_url
        command: if [[ -f .last_artifacts_url ]]; then cat .last_artifacts_url; fi
    - SetPropertyFromCommand:
        name: (switch) Last build success
        property: last_build_success
        command: if $(cat .last_final_status) == 'SUCCESSFUL'; then echo 'true'; fi
        doStepIf: '%(prop:last_artifacts_url:#?|true|false)s'
    - ShellCommand:
        name: Build was successful, skip it!
        command: exit 0
        doStepIf: '%(prop:last_build_success:#?|true|false)s'
    - ShellCommand:
        name: Build was not successful, try it!
        command: exit 0
        doStepIf: '%(prop:last_build_success:#?|false|true)s'
    - ShellCommand:
        name: Set build status to 'SUCCESSFUL'
        command: mkdir -p build_status && echo -n 'SUCCESSFUL' > build_status/.final_status
        haltOnFailure: true
        hideStepIf: true
    - Upload:
        name: Upload final status to artifacts
        source: build_status
        alwaysRun: true
        hideStepIf: true
