apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: storage-operator
rules:
# For recording transition events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
# For setting up monitoring for itself
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
# For reading its own name and namespace
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
# For managing its lock
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - storage-operator-lock
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  # NOTE: cannot scope "create" to a resourceName, see
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources
  - create
# For managing its own graceful termination
- apiGroups:
  - apps
  resourceNames:
  - storage-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
# For managing owned PVs
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - '*'
# For reading a Node's MetalK8s version
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  # NOTE: we only use "get" in code, but the controller-runtime tooling uses
  #       "list" and "watch" to manage a cache
  - list
  - watch
# For every custom resource from this Operator
- apiGroups:
  - storage.metalk8s.scality.com
  resources:
  - '*'
  verbs:
  - '*'
# For reading device preparation details (formatting and mounting options)
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
