---

- name: 'install prometheus-operator'
  helm_cli:
    release: '{{ prometheus_operator_release_name }}'
    chart:
      name: '{{ prometheus_operator_chart }}'
      version: '{{ prometheus_operator_version }}'
      repo: '{{ prometheus_operator_repo }}'
    namespace: '{{ prometheus_operator_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: '{{ prometheus_operator_external_values }}'
    timeout: '{{ prometheus_operator_timeout | int }}'
    wait: '{{ helm_wait | bool }}'
    state: '{{ helm_state }}'
  register: prometheus_operator_helm_install
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- debug:
    var: prometheus_operator_helm_install
  run_once: true
  when: debug | bool

- name: copy kube-prometheus additional dashboard manifests
  copy:
    src: 'additional-dashboards/{{ item }}.yml'
    dest: '{{ prometheus_addon_dir }}/'
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755
  with_items: '{{ kube_prometheus_dashboards }}'
  run_once: true
  delegate_to: '{{ groups["kube-master"][0] }}'

- name: deploy kube-prometheus additional dashboard manifests
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ prometheus_addon_dir }}/{{ item }}.yml'
    namespace: '{{ kube_prometheus_namespace }}'
    state: 'inplace-replaced'
  with_items: '{{ kube_prometheus_dashboards }}'
  run_once: true
  delegate_to: '{{ groups["kube-master"][0] }}'

- name: 'remove old exporter-node objects (#113)'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    namespace: '{{ kube_prometheus_namespace }}'
    label: chart=exporter-node-0.4.0,release=exporter-node
    resource: configmap,service,servicemonitor,endpoints
    state: 'absent'
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'get prometheus crd'
  command: >-
    {{ bin_dir }}/kubectl get
    customresourcedefinitions
    alertmanagers.monitoring.coreos.com
    prometheuses.monitoring.coreos.com
    servicemonitors.monitoring.coreos.com
  register: prometheus_crd
  run_once: True
  until: prometheus_crd is success
  check_mode: False
  changed_when: False
  retries: 10

- name: 'install kube-prometheus'
  helm_cli:
    release: '{{ kube_prometheus_release_name }}'
    chart:
      name: '{{ kube_prometheus_chart }}'
      version: '{{ kube_prometheus_version }}'
      repo: '{{ kube_prometheus_repo }}'
    namespace: '{{ kube_prometheus_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: >-
      {{ [
        lookup('template', 'prometheus_values.yml')
      ] + kube_prometheus_external_values }}
    wait: '{{ helm_wait | bool }}'
    state: '{{ helm_state }}'
  register: kube_prometheus_helm_install
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- debug:
    var: kube_prometheus_helm_install
  run_once: true
  when: debug | bool
